// Fake data for UI/UX demo — replace with real API calls later

export const FAKE_STUDENT = {
  user_id: 1,
  user_name: 'Lim Wei Jie',
  user_email: 'weijie@campus.edu.my',
  user_role: 'user',
  user_created_at: '2024-08-15T10:00:00Z',
}

export const FAKE_ADMIN = {
  user_id: 2,
  user_name: 'Dr. Siti Nur',
  user_email: 'siti.nur@campus.edu.my',
  user_role: 'admin',
  user_created_at: '2023-01-10T08:00:00Z',
}

export const FACILITIES = [
  {
    facility_id: 1,
    facility_name: 'Discussion Room A',
    facility_capacity: 8,
    facility_type: 'room',
    facility_description: 'A quiet discussion room equipped with a whiteboard, projector, and video conferencing capabilities. Perfect for small group meetings and study sessions.',
    facility_image_url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&q=80',
    facility_status: 'open',
  },
  {
    facility_id: 2,
    facility_name: 'Discussion Room B',
    facility_capacity: 10,
    facility_type: 'room',
    facility_description: 'Spacious discussion room with modular furniture, dual monitors, and natural lighting. Ideal for group projects and presentations.',
    facility_image_url: 'https://images.unsplash.com/photo-1577412647305-991150c7d163?w=600&q=80',
    facility_status: 'open',
  },
  {
    facility_id: 3,
    facility_name: 'Conference Hall',
    facility_capacity: 50,
    facility_type: 'room',
    facility_description: 'A large conference hall with a full PA system, stage, projection screen, and theater-style seating. Suitable for seminars, talks, and events.',
    facility_image_url: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=600&q=80',
    facility_status: 'open',
  },
  {
    facility_id: 4,
    facility_name: 'Study Pod 1',
    facility_capacity: 4,
    facility_type: 'room',
    facility_description: 'An intimate study pod with sound-dampening walls, standing desk option, and a 32-inch monitor. Great for focused individual or pair work.',
    facility_image_url: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=80',
    facility_status: 'closed',
  },
  {
    facility_id: 5,
    facility_name: 'Basketball Court',
    facility_capacity: 20,
    facility_type: 'court',
    facility_description: 'Full-size indoor basketball court with polished hardwood flooring, adjustable hoops, and LED lighting. Suitable for games and training.',
    facility_image_url: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=600&q=80',
    facility_status: 'open',
  },
  {
    facility_id: 6,
    facility_name: 'Badminton Court',
    facility_capacity: 8,
    facility_type: 'court',
    facility_description: 'Two regulation-size badminton courts with premium lighting and sprung flooring. Rackets and shuttlecocks available at the equipment counter.',
    facility_image_url: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=600&q=80',
    facility_status: 'open',
  },
  {
    facility_id: 7,
    facility_name: 'Projector Set A',
    facility_capacity: 1,
    facility_type: 'equipment',
    facility_description: 'Full HD portable projector (4000 lumens) with tripod stand, HDMI/USB-C cables, and carry case. Collect from the equipment counter with your booking QR.',
    facility_image_url: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=600&q=80',
    facility_status: 'open',
  },
  {
    facility_id: 8,
    facility_name: 'Video Recording Kit',
    facility_capacity: 1,
    facility_type: 'equipment',
    facility_description: 'Professional video recording kit including DSLR camera, tripod, LED ring light, and lavalier microphone. Suitable for video assignments and projects.',
    facility_image_url: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=600&q=80',
    facility_status: 'closed',
  },
]

export const BOOKINGS = [
  {
    booking_id: 1,
    user_id: 1,
    facility_id: 1,
    facility_name: 'Discussion Room A',
    booking_date: '2026-06-10',
    booking_time_slot: '10:00-11:00',
    booking_group_size: 5,
    booking_status: 'booked',
    booking_cancel_reason: null,
    booking_created_at: '2026-06-04T08:30:00Z',
  },
  {
    booking_id: 2,
    user_id: 1,
    facility_id: 5,
    facility_name: 'Basketball Court',
    booking_date: '2026-06-11',
    booking_time_slot: '15:00-16:00',
    booking_group_size: 10,
    booking_status: 'booked',
    booking_cancel_reason: null,
    booking_created_at: '2026-06-04T09:00:00Z',
  },
  {
    booking_id: 3,
    user_id: 1,
    facility_id: 3,
    facility_name: 'Conference Hall',
    booking_date: '2026-06-05',
    booking_time_slot: '14:00-15:00',
    booking_group_size: 30,
    booking_status: 'booked',
    booking_cancel_reason: null,
    booking_created_at: '2026-06-03T14:00:00Z',
  },
  {
    booking_id: 4,
    user_id: 1,
    facility_id: 2,
    facility_name: 'Discussion Room B',
    booking_date: '2026-06-03',
    booking_time_slot: '09:00-10:00',
    booking_group_size: 7,
    booking_status: 'checked-in',
    booking_cancel_reason: null,
    booking_created_at: '2026-06-01T10:00:00Z',
  },
  {
    booking_id: 5,
    user_id: 1,
    facility_id: 6,
    facility_name: 'Badminton Court',
    booking_date: '2026-06-02',
    booking_time_slot: '17:00-18:00',
    booking_group_size: 4,
    booking_status: 'checked-in',
    booking_cancel_reason: null,
    booking_created_at: '2026-05-30T11:30:00Z',
  },
  {
    booking_id: 6,
    user_id: 1,
    facility_id: 7,
    facility_name: 'Projector Set A',
    booking_date: '2026-05-28',
    booking_time_slot: '11:00-12:00',
    booking_group_size: 1,
    booking_status: 'checked-in',
    booking_cancel_reason: null,
    booking_created_at: '2026-05-26T09:00:00Z',
  },
  {
    booking_id: 7,
    user_id: 1,
    facility_id: 1,
    facility_name: 'Discussion Room A',
    booking_date: '2026-05-25',
    booking_time_slot: '13:00-14:00',
    booking_group_size: 3,
    booking_status: 'no-show',
    booking_cancel_reason: null,
    booking_created_at: '2026-05-23T16:00:00Z',
  },
  {
    booking_id: 8,
    user_id: 1,
    facility_id: 5,
    facility_name: 'Basketball Court',
    booking_date: '2026-05-20',
    booking_time_slot: '16:00-17:00',
    booking_group_size: 8,
    booking_status: 'no-show',
    booking_cancel_reason: null,
    booking_created_at: '2026-05-18T12:00:00Z',
  },
  {
    booking_id: 9,
    user_id: 1,
    facility_id: 2,
    facility_name: 'Discussion Room B',
    booking_date: '2026-05-15',
    booking_time_slot: '10:00-11:00',
    booking_group_size: 6,
    booking_status: 'cancelled',
    booking_cancel_reason: 'Rescheduling to a later date',
    booking_created_at: '2026-05-13T08:00:00Z',
  },
  {
    booking_id: 10,
    user_id: 1,
    facility_id: 3,
    facility_name: 'Conference Hall',
    booking_date: '2026-05-10',
    booking_time_slot: '08:00-09:00',
    booking_group_size: 25,
    booking_status: 'cancelled',
    booking_cancel_reason: 'Event postponed by organiser',
    booking_created_at: '2026-05-08T10:00:00Z',
  },
  {
    booking_id: 11,
    user_id: 1,
    facility_id: 6,
    facility_name: 'Badminton Court',
    booking_date: '2026-06-12',
    booking_time_slot: '08:00-09:00',
    booking_group_size: 4,
    booking_status: 'booked',
    booking_cancel_reason: null,
    booking_created_at: '2026-06-04T11:00:00Z',
  },
  {
    booking_id: 12,
    user_id: 1,
    facility_id: 7,
    facility_name: 'Projector Set A',
    booking_date: '2026-05-05',
    booking_time_slot: '12:00-13:00',
    booking_group_size: 1,
    booking_status: 'cancelled',
    booking_cancel_reason: 'Admin: Facility under maintenance',
    booking_created_at: '2026-05-03T07:30:00Z',
  },
]

export const NOTIFICATIONS = [
  {
    notification_id: 1,
    user_id: null,
    notification_message: '🏀 Basketball Court will be closed for resurfacing from 14–16 June. Plan your bookings accordingly.',
    notification_created_at: '2026-06-04T07:00:00Z',
    is_read: false,
  },
  {
    notification_id: 2,
    user_id: null,
    notification_message: '📢 New facility added: Video Recording Kit is now available for booking. Check it out under Equipment.',
    notification_created_at: '2026-06-02T09:00:00Z',
    is_read: false,
  },
  {
    notification_id: 3,
    user_id: 1,
    notification_message: '✅ Your booking for Discussion Room A on 10 Jun (10:00–11:00) has been confirmed.',
    notification_created_at: '2026-06-04T08:31:00Z',
    is_read: false,
  },
  {
    notification_id: 4,
    user_id: 1,
    notification_message: '❌ Your booking for Projector Set A on 5 May has been cancelled. Reason: Facility under maintenance.',
    notification_created_at: '2026-05-04T10:00:00Z',
    is_read: true,
  },
  {
    notification_id: 5,
    user_id: null,
    notification_message: '⚠️ Reminder: QR check-in must be done within 15 minutes of your booking slot start time to avoid a no-show.',
    notification_created_at: '2026-05-01T08:00:00Z',
    is_read: true,
  },
  {
    notification_id: 6,
    user_id: 1,
    notification_message: '🚫 You have been marked as a no-show for Discussion Room A on 25 May. Repeated no-shows may affect booking privileges.',
    notification_created_at: '2026-05-25T13:20:00Z',
    is_read: true,
  },
]

export const FAVOURITES = [
  { favourite_id: 1, user_id: 1, facility_id: 1 },
  { favourite_id: 2, user_id: 1, facility_id: 5 },
  { favourite_id: 3, user_id: 1, facility_id: 2 },
  { favourite_id: 4, user_id: 1, facility_id: 7 },
]

// All bookings across all users (for admin view)
export const ALL_BOOKINGS = [
  ...BOOKINGS,
  {
    booking_id: 13,
    user_id: 3,
    user_name: 'Aisha Binti Razak',
    facility_id: 2,
    facility_name: 'Discussion Room B',
    booking_date: '2026-06-10',
    booking_time_slot: '14:00-15:00',
    booking_group_size: 6,
    booking_status: 'booked',
    booking_cancel_reason: null,
    booking_created_at: '2026-06-04T10:00:00Z',
  },
  {
    booking_id: 14,
    user_id: 4,
    user_name: 'Tan Chee Keong',
    facility_id: 5,
    facility_name: 'Basketball Court',
    booking_date: '2026-06-09',
    booking_time_slot: '16:00-17:00',
    booking_group_size: 12,
    booking_status: 'checked-in',
    booking_cancel_reason: null,
    booking_created_at: '2026-06-03T15:00:00Z',
  },
  {
    booking_id: 15,
    user_id: 5,
    user_name: 'Priya Subramaniam',
    facility_id: 3,
    facility_name: 'Conference Hall',
    booking_date: '2026-06-08',
    booking_time_slot: '09:00-10:00',
    booking_group_size: 40,
    booking_status: 'no-show',
    booking_cancel_reason: null,
    booking_created_at: '2026-06-01T11:00:00Z',
  },
]

// Time slots available for booking
export const TIME_SLOTS = [
  '08:00-09:00',
  '09:00-10:00',
  '10:00-11:00',
  '11:00-12:00',
  '12:00-13:00',
  '13:00-14:00',
  '14:00-15:00',
  '15:00-16:00',
  '16:00-17:00',
  '17:00-18:00',
]

// Slots already booked (facility_id + date + slot) — for double-booking check demo
export const BOOKED_SLOTS = [
  { facility_id: 1, date: '2026-06-10', slot: '10:00-11:00' },
  { facility_id: 5, date: '2026-06-11', slot: '15:00-16:00' },
  { facility_id: 3, date: '2026-06-05', slot: '14:00-15:00' },
]

// Dashboard stats for admin
export const DASHBOARD_STATS = {
  totalBookings: 47,
  checkedIn: 18,
  noShows: 6,
  cancelled: 5,
  activeFacilities: 6,
  totalFacilities: 8,
  totalUsers: 124,
}

export const MONTHLY_BOOKINGS = [
  { month: 'Jan', bookings: 32, checkins: 25, noShows: 4 },
  { month: 'Feb', bookings: 28, checkins: 22, noShows: 3 },
  { month: 'Mar', bookings: 41, checkins: 35, noShows: 5 },
  { month: 'Apr', bookings: 38, checkins: 30, noShows: 6 },
  { month: 'May', bookings: 52, checkins: 42, noShows: 7 },
  { month: 'Jun', bookings: 47, checkins: 18, noShows: 6 },
]

export const FACILITY_USAGE = [
  { name: 'Discussion Rooms', value: 38, color: '#059669' },
  { name: 'Courts', value: 28, color: '#0ea5e9' },
  { name: 'Conference Hall', value: 24, color: '#f59e0b' },
  { name: 'Equipment', value: 10, color: '#8b5cf6' },
]
